---
title: "Introduction to CoPheScan"
author: "Ichcha Manipur"
date: "2023-03-30"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to CoPheScan}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figure/Intro-"
)
```

```{r setup, message=F, warning=F}
library(cophescan)
library(ggplot2)
#library(ggpubr)
```

#### Load data  

```{r message=F, warning=F }
data("cophe_multi_trait_data")
attach(cophe_multi_trait_data)
names(cophe_multi_trait_data)
```

The dataset contains the summary statistics of 30 traits with 10 traits each simulated to have high posterior probability of Hc (shared causal variant), Ha and Hn.

The query variant is `r toString(query.snpid)`

#### Single trait
```{r fig.width = 4, fig.height=4, fig.align = "center"}
trait1 <- cophe_multi_trait_data$summ_stat[['Trait_1']] 
query.snpid <- cophe_multi_trait_data$query.snpid
trait1$position <- sapply(trait1$snp, function(x) as.numeric(unlist(strsplit(x, "-"))[2]))
plot_trait_manhat(trait1, query.snpid)

# Run cophescan under a single causal variant assumption by providing the snpid of the known causal variant for trait 1 = query.snpid
res.single <- cophe.single(trait1, query.snpid = query.snpid, querytrait='Trait_1')
summary(res.single)
# Run cophescan with susie (multiple variants) by providing the snpid of the known causal variant for trait 1 = query.snpid
trait1$LD <- LD
res.susie <- cophe.susie(trait1, query.snpid = query.snpid, querytrait='Trait_1')
summary(res.susie)
```


#### Multi-trait analysis
```{r message=F, warning=F, results='hide'}
## Hide print messages from coloc
co <-  capture.output(res.multi <- cophe.multitrait(cophe_multi_trait_data$summ_stat, query.snpid = query.snpid, querytrait.names = names(cophe_multi_trait_data$summ_stat), method = 'single', simplify = T, predict.hyp = T))
# res.multi <- cophe.multitrait(cophe_multi_trait_data$summ_stat, query.snpid = query.snpid, querytrait.names = names(cophe_multi_trait_data$summ_stat), method = 'susie', LDmat = cophe_multi_trait_data$LD)
```

##### **Plot cophescan results**
```{r fig.show='hold',fig.height=3, fig.width=4.5, out.width = "48.5%",  fig.ncol = 2, message=F, warning=F}
cophe.plots.res <- cophe_plot(res.multi, traits.dat = cophe_multi_trait_data$summ_stat, query.snpid = query.snpid)
# ggpubr::ggarrange(cophe.plots.res$pval, cophe.plots.res$ppHa, cophe.plots.res$ppHc, ncol = 2, nrow = 2) + ggplot2::theme(text = ggplot2::element_text(size=2))
cophe.plots.res$pval
cophe.plots.res$ppHc
cophe.plots.res$ppHa
```

##### **cophescan Ternary plots** 
```{r fig.show='hold',fig.height=5, fig.width=5, out.width = "48.5%",  fig.ncol = 2, message=F, warning=F}
plot_cophe_ternary(res.multi)
plot_cophe_ternary(res.multi, traits.dat = cophe_multi_trait_data$summ_stat, plot_pval = T)
```

#### Run hierarchical model for priors
```{r warning=F, message=F, fig.width = 5, fig.height=5, fig.align = "center"}
rg=F
# rg=T
co <-  capture.output(res.multi <- cophe.multitrait(cophe_multi_trait_data$summ_stat, query.snpid = query.snpid, querytrait.names = names(cophe_multi_trait_data$summ_stat), method = 'single', simplify = T, predict.hyp = F))
cophe.hier.res <- run_metrop_priors(res.multi, posterior = T, avg_posterior=T, pik=T, avg_pik = T, rg_vec = cophe_multi_trait_data$rg_vec, rg = rg, nits = 30000) 
loglik <- cophe.hier.res$ll
parameters <- cophe.hier.res$parameters
col <- rgb(red = 0.4, green = 0.7, blue = 0.5, alpha = 0.8)
par(mfrow=c(2,2))
plot(1:length(loglik), loglik, main="loglik",type="l", col=col, ylab = "ll", xlab="")
plot(1:ncol(parameters), parameters[1,], main="alpha",type="l", col=col, ylab = "alpha", xlab="")
plot(1:ncol(parameters), parameters[2,], main="beta",type="l", col=col, ylab = "beta", xlab="")
if (rg == T)
  plot(1:ncol(parameters), parameters[3,], main="gamma",type="l", col=col, ylab = "gamma", xlab="")
# summary(cophe.hier.res$avg.pik)
```
