// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pars2pik_norg
arma::mat pars2pik_norg(NumericVector pars, NumericVector nsnps);
RcppExport SEXP _cophescan_pars2pik_norg(SEXP parsSEXP, SEXP nsnpsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nsnps(nsnpsSEXP);
    rcpp_result_gen = Rcpp::wrap(pars2pik_norg(pars, nsnps));
    return rcpp_result_gen;
END_RCPP
}
// pars2pik_rg
arma::mat pars2pik_rg(NumericVector pars, NumericVector nsnps, NumericVector rg_vec);
RcppExport SEXP _cophescan_pars2pik_rg(SEXP parsSEXP, SEXP nsnpsSEXP, SEXP rg_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nsnps(nsnpsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rg_vec(rg_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(pars2pik_rg(pars, nsnps, rg_vec));
    return rcpp_result_gen;
END_RCPP
}
// pars2pik
arma::mat pars2pik(NumericVector pars, NumericVector nsnps, NumericVector rg_vec, bool rg);
RcppExport SEXP _cophescan_pars2pik(SEXP parsSEXP, SEXP nsnpsSEXP, SEXP rg_vecSEXP, SEXP rgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nsnps(nsnpsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rg_vec(rg_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type rg(rgSEXP);
    rcpp_result_gen = Rcpp::wrap(pars2pik(pars, nsnps, rg_vec, rg));
    return rcpp_result_gen;
END_RCPP
}
// logsumexp
double logsumexp(arma::rowvec x);
RcppExport SEXP _cophescan_logsumexp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logsumexp(x));
    return rcpp_result_gen;
END_RCPP
}
// logpost
arma::mat logpost(NumericVector pars, arma::mat lbf_mat, NumericVector nsnps, NumericVector rg_vec, bool rg);
RcppExport SEXP _cophescan_logpost(SEXP parsSEXP, SEXP lbf_matSEXP, SEXP nsnpsSEXP, SEXP rg_vecSEXP, SEXP rgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lbf_mat(lbf_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nsnps(nsnpsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rg_vec(rg_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type rg(rgSEXP);
    rcpp_result_gen = Rcpp::wrap(logpost(pars, lbf_mat, nsnps, rg_vec, rg));
    return rcpp_result_gen;
END_RCPP
}
// loglik
double loglik(NumericVector pars, arma::mat lbf_mat, NumericVector nsnps, NumericVector rg_vec, bool rg);
RcppExport SEXP _cophescan_loglik(SEXP parsSEXP, SEXP lbf_matSEXP, SEXP nsnpsSEXP, SEXP rg_vecSEXP, SEXP rgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lbf_mat(lbf_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nsnps(nsnpsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rg_vec(rg_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type rg(rgSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik(pars, lbf_mat, nsnps, rg_vec, rg));
    return rcpp_result_gen;
END_RCPP
}
// posterior
arma::mat posterior(NumericVector pars, arma::mat lbf_mat, NumericVector nsnps, NumericVector rg_vec, bool rg);
RcppExport SEXP _cophescan_posterior(SEXP parsSEXP, SEXP lbf_matSEXP, SEXP nsnpsSEXP, SEXP rg_vecSEXP, SEXP rgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lbf_mat(lbf_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nsnps(nsnpsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rg_vec(rg_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type rg(rgSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior(pars, lbf_mat, nsnps, rg_vec, rg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cophescan_pars2pik_norg", (DL_FUNC) &_cophescan_pars2pik_norg, 2},
    {"_cophescan_pars2pik_rg", (DL_FUNC) &_cophescan_pars2pik_rg, 3},
    {"_cophescan_pars2pik", (DL_FUNC) &_cophescan_pars2pik, 4},
    {"_cophescan_logsumexp", (DL_FUNC) &_cophescan_logsumexp, 1},
    {"_cophescan_logpost", (DL_FUNC) &_cophescan_logpost, 5},
    {"_cophescan_loglik", (DL_FUNC) &_cophescan_loglik, 5},
    {"_cophescan_posterior", (DL_FUNC) &_cophescan_posterior, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_cophescan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
