# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Conversion of parameters α, β and γ to p0k, pak and pck
#'
#' @param params Vector of parameters: α, β and γ
#' @param nsnps number of snps
#' @param rg_vec Vector of the covariate
#' @param rg logical: should the covariate information be used? default: False
#' @return pik matrix of priors: p0k, pak and pck
pars2pik <- function(params, nsnps, rg_vec, rg = FALSE) {
    .Call(`_cophescan_pars2pik`, params, nsnps, rg_vec, rg)
}

#' Log sum
#' @param x vector of log scale values to be added
logsumexp <- function(x) {
    .Call(`_cophescan_logsumexp`, x)
}

#' Log posterior calculation
#'
#' @param params Vector of parameters: α, β and γ
#' @param lbf_mat matrix of log bayes factors: lbfak and lbfck
#' @param nsnps number of snps
#' @param rg_vec Vector of the covariate
#' @param rg logical: should the covariate inflormation be used? default: False
#' @return logpost flog of the posteriors
logpost <- function(params, lbf_mat, nsnps, rg_vec, rg = FALSE) {
    .Call(`_cophescan_logpost`, params, lbf_mat, nsnps, rg_vec, rg)
}

#' Log likelihood calculation
#'
#' @param params Vector of parameters: α, β and γ
#' @param lbf_mat matrix of log bayes factors: lbfak and lbfck
#' @param nsnps number of snps
#' @param rg_vec Vector of the covariate
#' @param rg logical: should the covariate inflormation be used? default: False
#' @return logpost flog of the posteriors
loglik <- function(params, lbf_mat, nsnps, rg_vec, rg = FALSE) {
    .Call(`_cophescan_loglik`, params, lbf_mat, nsnps, rg_vec, rg)
}

#' Calculation of the posterior prob of Hn, Ha and Hc
#'
#' @param params Vector of parameters: α, β and γ
#' @param lbf_mat matrix of log bayes factors: lbfak and lbfck
#' @param nsnps number of snps
#' @param rg_vec Vector of the covariate
#' @param rg logical: should the covariate inflormation be used? default: False
#' @return posterior prob of Hn, Ha and Hc
get_posterior_prob <- function(params, lbf_mat, nsnps, rg_vec, rg = FALSE) {
    .Call(`_cophescan_get_posterior_prob`, params, lbf_mat, nsnps, rg_vec, rg)
}

#' sample alpha
#' @param alpha_mean prior for the mean of  alpha
#' @param alpha_sd prior for the standard deviation of  alpha
sample_alpha <- function(alpha_mean = -10, alpha_sd = -0.5) {
    .Call(`_cophescan_sample_alpha`, alpha_mean, alpha_sd)
}

#' sample beta
#' @param beta_shape prior for the shape (gamma distibution) of beta
#' @param beta_scale prior for the scale of beta
sample_beta <- function(beta_shape = 2, beta_scale = 2) {
    .Call(`_cophescan_sample_beta`, beta_shape, beta_scale)
}

#' sample gamma
#' @param gamma_shape prior for the shape (gamma distibution) of gamma
#' @param gamma_scale prior for the scale of gamma
sample_gamma <- function(gamma_shape = 2, gamma_scale = 2) {
    .Call(`_cophescan_sample_gamma`, gamma_shape, gamma_scale)
}

#' dnorm for alpha
#' @param a current alpha
#' @param alpha_mean prior for the mean of  alpha
#' @param alpha_sd prior for the standard deviation of  alpha
logd_alpha <- function(a, alpha_mean = -10, alpha_sd = 0.5) {
    .Call(`_cophescan_logd_alpha`, a, alpha_mean, alpha_sd)
}

#' dgamma for beta
#' @param b current beta
#' @param beta_shape prior for the shape (gamma distibution) of beta
#' @param beta_scale prior for the scale of beta
logd_beta <- function(b, beta_shape = 2, beta_scale = 2) {
    .Call(`_cophescan_logd_beta`, b, beta_shape, beta_scale)
}

#' dgamma for gamma
#' @param g current gamma
#' @param gamma_shape prior for the shape (gamma distibution) of gamma
#' @param gamma_scale prior for the scale of gamma
logd_gamma <- function(g, gamma_shape = 2, gamma_scale = 2) {
    .Call(`_cophescan_logd_gamma`, g, gamma_shape, gamma_scale)
}

#' Run the hierarchical mcmc model to infer priors
#' @param lbf_mat matrix of log bayes factors: lbfak and lbfck
#' @param nsnps number of snps
#' @param rg_vec Vector of the covariate
#' @param nits Number of iterations run in mcmc
#' @param thin thinning
#' @param rg logical: Should the covariate inflormation be used? default: False
#' @param alpha_mean prior for the mean of  alpha
#' @param alpha_sd prior for the standard deviation of  alpha
#' @param beta_shape prior for the shape (gamma distibution) of beta
#' @param beta_scale prior for the scale of beta
#' @param gamma_shape prior for the shape (gamma distibution) of gamma
#' @param gamma_scale prior for the scale of gamma
#' @return matrix with average of all the posterior probabilities: Hn, Ha and Hc
metrop_run <- function(lbf_mat, nsnps, rg_vec, rg = FALSE, nits = 10000L, thin = 1L, alpha_mean = -10, alpha_sd = 0.5, beta_shape = 2, beta_scale = 2, gamma_shape = 2, gamma_scale = 2) {
    .Call(`_cophescan_metrop_run`, lbf_mat, nsnps, rg_vec, rg, nits, thin, alpha_mean, alpha_sd, beta_shape, beta_scale, gamma_shape, gamma_scale)
}

#' Average of posterior probabilities: Hn, Ha and Hc
#'
#' @param params Vector of parameters: α, β and γ
#' @param lbf_mat matrix of log bayes factors: lbfak and lbfck
#' @param nsnps number of snps
#' @param rg_vec Vector of the covariate
#' @param rg logical: was the covariate inflormation  used? default: False
#' @return params List of posterior probabilties (len: iterations): Hn, Ha and Hc
posterior_prob <- function(params, lbf_mat, nsnps, rg_vec, rg = FALSE) {
    .Call(`_cophescan_posterior_prob`, params, lbf_mat, nsnps, rg_vec, rg)
}

#' Average of posterior probabilities: Hn, Ha and Hc
#'
#' @param params Vector of parameters: α, β and γ
#' @param nsnps number of snps
#' @param rg_vec Vector of the covariate
#' @param rg logical: was the covariate inflormation  used? default: False
#' @return List of priors (len: iterations): p0k, pak and pck
piks <- function(params, nsnps, rg_vec, rg = FALSE) {
    .Call(`_cophescan_piks`, params, nsnps, rg_vec, rg)
}

#' Average of posterior probabilities: Hn, Ha and Hc
#'
#' @param params Vector of parameters: α, β and γ
#' @param lbf_mat matrix of log bayes factors: lbfak and lbfck
#' @param nsnps number of snps
#' @param rg_vec Vector of the covariate
#' @param nits Number of iterations run in mcmc
#' @param thin thinning
#' @param rg logical: was the covariate inflormation  used? default: False
#' @return matrix with average of all the posterior probabilities: Hn, Ha and Hc
average_posterior_prob <- function(params, lbf_mat, nsnps, rg_vec, nits, thin, rg = FALSE) {
    .Call(`_cophescan_average_posterior_prob`, params, lbf_mat, nsnps, rg_vec, nits, thin, rg)
}

#' Average of priors: p0k, pak and pck
#'
#' @param params Vector of parameters: α, β and γ
#' @param nsnps number of snps
#' @param rg_vec Vector of the covariate
#' @param nits Number of iterations run in mcmc
#' @param thin thinning
#' @param rg logical: was the covariate inflormation  used? default: False
#' @return average pik matrix of priors: p0k, pak and pck
average_piks <- function(params, nsnps, rg_vec, nits, thin, rg = FALSE) {
    .Call(`_cophescan_average_piks`, params, nsnps, rg_vec, nits, thin, rg)
}

