# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pars2pik_norg <- function(pars, nsnps) {
    .Call(`_cophescan_pars2pik_norg`, pars, nsnps)
}

pars2pik_rg <- function(pars, nsnps, rg_vec) {
    .Call(`_cophescan_pars2pik_rg`, pars, nsnps, rg_vec)
}

pars2pik <- function(pars, nsnps, rg_vec = 0L, rg = FALSE) {
    .Call(`_cophescan_pars2pik`, pars, nsnps, rg_vec, rg)
}

logsumexp <- function(x) {
    .Call(`_cophescan_logsumexp`, x)
}

logpost <- function(pars, lbf_mat, nsnps, rg_vec = 0L, rg = FALSE) {
    .Call(`_cophescan_logpost`, pars, lbf_mat, nsnps, rg_vec, rg)
}

loglik <- function(pars, lbf_mat, nsnps, rg_vec = 0L, rg = FALSE) {
    .Call(`_cophescan_loglik`, pars, lbf_mat, nsnps, rg_vec, rg)
}

posterior <- function(pars, lbf_mat, nsnps, rg_vec = 0L, rg = FALSE) {
    .Call(`_cophescan_posterior`, pars, lbf_mat, nsnps, rg_vec, rg)
}

